catalog_name: mlops_dev
schema_name: sebastia
data_path: "dbfs:/Volumes/mlops_dev/sebastia/sebastian22/vgsales.csv"

num_features:
  - "NA_Sales"
  - "EU_Sales"
  - "JP_Sales"
  - "Other_Sales"
  - "Global_Sales"

cat_features:
  - "Platform"
  - "Genre"
  - "Publisher"

target: "Global_Sales"
